import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import {addToCart,cartView,completeCheckout,createCheckout,getCart,getCheckout,getProduct,money,recordProfiling,searchProducts} from './store.js';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../public');
const port=Number(process.env.PORT||3000),base=process.env.PUBLIC_BASE_URL||`http://localhost:${port}`;
const tools=[
{name:'search_products',title:'Search products',description:"Search the merchant catalog for physical products matching the user's request.",inputSchema:{type:'object',properties:{query:{type:'string'},maxPriceDollars:{type:'number',exclusiveMinimum:0}},additionalProperties:false},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false}},
{name:'get_product',title:'Get product',description:'Get current authoritative product details, price, and inventory by product ID.',inputSchema:{type:'object',properties:{productId:{type:'string'}},required:['productId'],additionalProperties:false},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false}},
{name:'add_to_cart',title:'Add product to cart',description:'Add a specific physical product and quantity to a cart. Creates a cart when cartId is omitted.',inputSchema:{type:'object',properties:{cartId:{type:'string'},productId:{type:'string'},quantity:{type:'integer',minimum:1,maximum:10}},required:['productId'],additionalProperties:false},annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false}},
{name:'get_cart',title:'Get cart',description:'Review cart items and totals before checkout.',inputSchema:{type:'object',properties:{cartId:{type:'string'}},required:['cartId'],additionalProperties:false},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false}},
{name:'checkout_session',title:'Start checkout',description:'Create a checkout session for the current cart and return the hosted checkout page. This does not charge the user.',inputSchema:{type:'object',properties:{cartId:{type:'string'}},required:['cartId'],additionalProperties:false},annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:true},_meta:{'openai/widgetAccessible':true,'ui/resourceUri':'ui://widget/checkout-session.html'}},
{name:'get_order_status',title:'Get order status',description:'Check whether a checkout was completed.',inputSchema:{type:'object',properties:{checkoutId:{type:'string'}},required:['checkoutId'],additionalProperties:false},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false}}];
const ok=(text,structuredContent={},meta)=>({content:[{type:'text',text}],structuredContent,...(meta?{_meta:meta}:{})});
function callTool(name,a={}){try{switch(name){case'search_products':{const ps=searchProducts(a.query||'',a.maxPriceDollars?Math.round(a.maxPriceDollars*100):undefined).map(p=>({...p,price:money(p.priceCents),url:`${base}/product.html?id=${p.id}`,image:`${base}${p.image}`}));return ok(ps.length?`Found ${ps.length} matching products.`:'No matching products found.',{products:ps})}case'get_product':{const p=getProduct(a.productId);if(!p)throw Error('Product not found');return ok(`${p.name} costs ${money(p.priceCents)} and has ${p.inventory} units available.`,{product:{...p,price:money(p.priceCents),url:`${base}/product.html?id=${p.id}`}})}case'add_to_cart':{const c=addToCart(a.cartId,a.productId,a.quantity||1),v=cartView(c);return ok(`Cart updated. Total is ${money(v.totalCents)}. Cart ID: ${c.id}`,{cart:v})}case'get_cart':{const c=getCart(a.cartId);if(!c)throw Error('Cart not found');const v=cartView(c);return ok(`Cart total: ${money(v.totalCents)}.`,{cart:v})}case'checkout_session':{const x=createCheckout(a.cartId),v=cartView(getCart(a.cartId)),url=`${base}/checkout.html?checkoutId=${x.id}`;return ok(`Checkout is ready at ${url}. The user must review and explicitly place the order on that page.`,{checkout:{id:x.id,status:x.status,url,cart:v}},{'openai/outputTemplate':'ui://widget/checkout-session.html'})}case'get_order_status':{const x=getCheckout(a.checkoutId);if(!x)throw Error('Checkout not found');return ok(`Checkout status: ${x.status}.`,{checkout:x})}default:throw Error('Unknown tool')}}catch(e){return{isError:true,content:[{type:'text',text:e.message}]}}}
function json(res,status,obj,headers={}){res.writeHead(status,{'content-type':'application/json',...headers});res.end(JSON.stringify(obj))}
async function body(req){let s='';for await(const c of req)s+=c;return s?JSON.parse(s):{}}
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml'};
http.createServer(async(req,res)=>{try{const u=new URL(req.url,base);if(u.pathname==='/mcp'){if(req.method!=='POST')return json(res,405,{error:'This is an MCP endpoint. Send JSON-RPC requests with POST; opening it in a browser will not list tools.'},{allow:'POST'});const r=await body(req),id=r.id??null;let result;if(r.method==='initialize')result={protocolVersion:'2025-06-18',capabilities:{tools:{}},serverInfo:{name:'sample-commerce',version:'1.0.0'},instructions:'Help users find physical products, maintain a cart, and begin checkout. Never claim an order is paid until checkout completes.'};else if(r.method==='tools/list')result={tools};else if(r.method==='tools/call')result=callTool(r.params?.name,r.params?.arguments);else if(r.method==='notifications/initialized'){res.writeHead(202);return res.end()}else return json(res,200,{jsonrpc:'2.0',id,error:{code:-32601,message:'Method not found'}});return json(res,200,{jsonrpc:'2.0',id,result})}
if(u.pathname==='/health')return json(res,200,{ok:true});if(u.pathname==='/api/products')return json(res,200,searchProducts(u.searchParams.get('q')||''));if(u.pathname==='/api/config'){const tmxOrgId=process.env.TMX_ORG_ID||'';return json(res,200,{tmxDomain:process.env.TMX_PROFILING_DOMAIN||'h.online-metrix.net',tmxOrgId,tmxConfigured:/^[A-Za-z0-9]{8}$/.test(tmxOrgId)})}
if(req.method==='POST'&&u.pathname==='/api/cart/items'){const a=await body(req),c=addToCart(a.cartId,a.productId,a.quantity||1);return json(res,200,{cart:cartView(c)})}
let cartMatch=u.pathname.match(/^\/api\/cart\/([^/]+)$/);if(req.method==='GET'&&cartMatch){const c=getCart(cartMatch[1]);if(!c)return json(res,404,{error:'Cart not found'});return json(res,200,{cart:cartView(c)})}
if(req.method==='POST'&&u.pathname==='/api/checkout'){const a=await body(req),x=createCheckout(a.cartId);return json(res,201,{checkout:x,url:`${base}/checkout.html?checkoutId=${x.id}`})}
let m=u.pathname.match(/^\/api\/checkout\/([^/]+)$/);if(req.method==='GET'&&m){const x=getCheckout(m[1]);if(!x)return json(res,404,{error:'Not found'});return json(res,200,{checkout:x,cart:cartView(getCart(x.cartId))})}m=u.pathname.match(/^\/api\/checkout\/([^/]+)\/complete$/);if(req.method==='POST'&&m){const x=getCheckout(m[1]);if(!x)return json(res,404,{error:'Not found'});const risk={decision:'accept',reason:'demo mode'};if(risk.decision!=='accept')return json(res,403,{error:'Order blocked by risk policy'});return json(res,200,{checkout:completeCheckout(m[1]),orderNumber:`DEMO-${Date.now()}`})}
m=u.pathname.match(/^\/api\/checkout\/([^/]+)\/profiling$/);if(req.method==='POST'&&m){const a=await body(req),x=recordProfiling(m[1],a.status);return json(res,200,{profiling:x.profiling})}
let file=u.pathname==='/'?'/index.html':u.pathname;const full=path.resolve(root,'.'+file);if(!full.startsWith(root)||!fs.existsSync(full)||fs.statSync(full).isDirectory()){res.writeHead(404);return res.end('Not found')}res.writeHead(200,{'content-type':mime[path.extname(full)]||'application/octet-stream'});fs.createReadStream(full).pipe(res)}catch(e){json(res,500,{error:e.message})}}).listen(port,()=>console.log(`Shop: ${base}\nMCP: ${base}/mcp`));
